
project_id = "jmqpqgxqhfctyfjtlbbm"

[functions.parcel-panel-webhook]
verify_jwt = false

[functions.update-shopify-fulfillment]
verify_jwt = false

[functions.shopify-held-orders]
verify_jwt = false

[functions.sync-shopify-order-stage]
verify_jwt = false
