// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fmhwcnjvlagoilicsmuw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZtaHdjbmp2bGFnb2lsaWNzbXV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgyNTg0NzMsImV4cCI6MjA5MzgzNDQ3M30.4cw5j5mFu-ZJ4OVm2y1YM0t74ssa2q7fR0oNMWvblSg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
