// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jmqpqgxqhfctyfjtlbbm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImptcXBxZ3hxaGZjdHlmanRsYmJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4Nzk5MzksImV4cCI6MjA2NzQ1NTkzOX0.-yFmt-q8qrob0h_nUFt_aYRaU6cw0XSAkyjXVx4bgHE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});